name: CI

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-build-backend:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1 (SHA)
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0 (SHA)
        with:
          node-version: "24" # recommended version for production (active LTS)
          package-manager-cache: false
      - run: npm ci
      - run: npx prisma generate
      - run: npm run lint
      - run: npm run build

  lint-build-frontend:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1 (SHA)
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0 (SHA)
        with:
          node-version: "24" # recomended version for production (active LTS)
          package-manager-cache: false
      - run: npm ci
      - run: npm run lint
      - run: npm run build
